export const GET_CURRENCIES = "GET_CURRENCIES";
export const SEARCH_CURRENCY = "SEARCH_CURRENCY";
export const SORT_CURRENCIES = "SORT_CURRENCIES";
export const CLEAR_SEARCH_INPUT = "CLEAR_SEARCH_INPUT";